Fixed crasher bug with muf process kill while handling mufevent. Fixed bug with GETPIDINFO returning timer event info for a process. Fixed hanging bug in fbmuck init script, when fbmuck errors out. Changed SSL cert/key load failures to just disable SSL, instead of exiting. Changed SSL cert/key load failure error reporting to show file path/name. Changed commandline to accept -sport with a warning when SSL not supported.

diff --git a/scripts/fbmuck-sysvinit b/scripts/fbmuck-sysvinit
--- a/scripts/fbmuck-sysvinit
+++ b/scripts/fbmuck-sysvinit
@@ -65,19 +65,28 @@ case "$cmd" in
         if [ "x$who" = "xroot" -o "x$who" = "x$user" ]; then
             ports=`echo $ports | sed 's/,/ /g' | sed 's/\([0-9]*\)s/-sport \1/g'`
             rm -f $path/$pidfile
-			if [ -x "$path/$script" ]; then
-				echo -n "$name "
-				if [ "x$who" = "x$user" ]; then
-					$path/$script $ports >> /dev/null 2>&1
-				else
-					su - $user -c "$path/$script $ports >> /dev/null 2>&1"
-				fi
-				while [ ! -f $path/$pidfile ]; do
-					sleep 1
-				done
-			else
-				echo "Cannot execute restart script $path/$script"
-			fi
+            if [ -x "$path/$script" ]; then
+                echo -n "$name "
+                failed=0
+                if [ "x$who" = "x$user" ]; then
+                    $path/$script $ports
+                    if [ $? != 0 ]; then
+                        failed=1
+                    fi
+                else
+                    rcode=`su $user -c "$path/$script $ports; echo $?"`
+                    if [ "$rcode" != 0 ]; then
+                        failed=1
+                    fi
+                fi
+                if [ $failed == 0 ]; then
+                    while [ ! -f $path/$pidfile ]; do
+                        sleep 1
+                    done
+                fi
+            else
+                echo "Cannot execute restart script $path/$script"
+            fi
         fi
     done
     echo ""
